cro_str = input()
cro_str = cro_str.replace('c=', '1')
cro_str = cro_str.replace('c-', '2')
cro_str = cro_str.replace('dz=', '3')
cro_str = cro_str.replace('d-', '4')
cro_str = cro_str.replace('lj', '5')
cro_str = cro_str.replace('nj', '6')
cro_str = cro_str.replace('s=', '7')
cro_str = cro_str.replace('z=', '8')

print(len(cro_str))